FROM tzapu/development-meteor
RUN apt-get install -y sudo && \
	adduser user && \
	echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user && \
	chmod 0440 /etc/sudoers.d/user 
WORKDIR /opt/app/
ADD .storybook /opt/app/
ADD . /opt/app/

CMD ["su", "user", "-c", "npm run storybook -c storybook"]