export const SET_ACTIVE_TREE_ITEMS = 'SET_ACTIVE_TREE_ITEMS';
export const SET_EXPANDED_TREE_ITEMS = 'SET_EXPANDED_TREE_ITEMS';
export const SET_ACTIVE_SEARCH = 'SET_ACTIVE_SEARCH';
export const FILE_TREE_COLLAPSE = 'FILE_TREE_COLLAPSE';