FROM busybox

ADD packages/nuxeo-api-playground-1.1.1.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-showcase-content-1.1.2.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-virtualnavigation-1.2.3.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/platform-explorer-1.6.3.zip 							/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-template-rendering-samples-6.6.2.zip 			/docker-entrypoint-initnuxeo.d/
ADD packages/fs-exporter-1.4.2.zip 									/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-agenda-1.4.1.zip 								/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-box-api-1.3.3.zip 								/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-cc-connector-marketplace-1.2.1-SNAPSHOT.zip 		/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-groups-rights-audit-1.8.2.zip 					/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-imap-connector-1.2.3.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-jenkins-report-mp-3.8.3.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-mediapublishing-1.2.3.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-platform-importer-1.7.2.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-platform-smart-search-1.8.3.zip 					/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-review-workflows-dashboards-1.1.2.zip 			/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-signature-2.5.2.zip 								/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-template-rendering-6.6.2.zip 					/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-vision-1.1.3.zip 								/docker-entrypoint-initnuxeo.d/
ADD packages/easyshare-1.3.3.zip 									/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-csv-1.5.3.zip 									/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-diff-1.7.2.zip 									/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-diff-pictures-1.1.2.zip 							/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-drive-1.6.2.zip 									/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-liveconnect-1.1.2.zip 							/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-multi-tenant-1.6.3.zip 							/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-platform-user-registration-1.7.2.zip 			/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-quota-1.6.2.zip 									/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-spreadsheet-1.2.2.zip 							/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-timeoff-1.0.7.zip 								/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-travel-expenses-1.1.2.zip 						/docker-entrypoint-initnuxeo.d/
ADD packages/nuxeo-web-ui-0.7.0.zip 								/docker-entrypoint-initnuxeo.d/

ADD docker /docker-entrypoint-initnuxeo.d/

VOLUME /docker-entrypoint-initnuxeo.d/

RUN /bin/true