export const UPLOAD_QUEUE_ADD_FILE = 'UPLOAD_QUEUE_ADD_FILE';
export const UPLOAD_QUEUE_ADD_MULTIPLE = 'UPLOAD_QUEUE_ADD_MULTIPLE';
export const UPLOAD_QUEUE_REMOVE_FILE = 'UPLOAD_QUEUE_REMOVE_FILE';

export const UPLOAD_QUEUE_SELECT = 'UPLOAD_QUEUE_SELECT';
export const UPLOAD_QUEUE_FILE_INFO = 'UPLOAD_QUEUE_FILE_INFO';
export const UPLOAD_QUEUE_FILE_INFO_REMOVE = 'UPLOAD_QUEUE_FILE_INFO_REMOVE';

export const UPLOAD_QUEUE_MOVE_WAIT_TO_INPROGRESS = 'UPLOAD_QUEUE_MOVE_WAIT_TO_INPROGRESS';
export const UPLOAD_QUEUE_UPDATE_FILE_STATUS_COMPLETE = 'UPLOAD_QUEUE_UPDATE_FILE_STATUS_COMPLETE';

export const UPLOAD_QUEUE_REMOVE_SELECTED = 'UPLOAD_QUEUE_REMOVE_SELECTED';
export const UPLOAD_QUEUE_START_SELECTED = 'UPLOAD_QUEUE_START_SELECTED';
export const UPLOAD_QUEUE_CANCEL_SELECTED = 'UPLOAD_QUEUE_CANCEL_SELECTED';
export const UPLOAD_QUEUE_RESUME_SELECTED = 'UPLOAD_QUEUE_RESUME_SELECTED';
export const UPLOAD_QUEUE_PAUSE_SELECTED = 'UPLOAD_QUEUE_PAUSE_SELECTED';

export const UPLOAD_QUEUE_REMOVE_ALL = 'UPLOAD_QUEUE_REMOVE_ALL';
export const UPLOAD_QUEUE_START_ALL = 'UPLOAD_QUEUE_START_ALL';
export const UPLOAD_QUEUE_START_ALL_W_WAIT = 'UPLOAD_QUEUE_START_ALL_W_WAIT';
export const UPLOAD_QUEUE_START_ALL_W_OUT_WAIT = 'UPLOAD_QUEUE_START_ALL_W_OUT_WAIT';
export const UPLOAD_QUEUE_PAUSE_ALL = 'UPLOAD_QUEUE_PAUSE_ALL';
export const UPLOAD_QUEUE_RESUME_ALL = 'UPLOAD_QUEUE_RESUME_ALL';
export const UPLOAD_QUEUE_CANCEL_ALL = 'UPLOAD_QUEUE_CANCEL_ALL';

export const UPLOAD_FILE_START = 'UPLOAD_FILE_START';
export const UPLOAD_FILE_PAUSE = 'UPLOAD_FILE_PAUSE';
export const UPLOAD_FILE_CANCEL = 'UPLOAD_FILE_CANCEL';
export const UPLOAD_FILE_RESUME = 'UPLOAD_FILE_RESUME';

export const UPLOAD_DIALOG_OPEN = 'UPLOAD_DIALOG_OPEN';

export const UPLOAD_SET_MATTER = 'UPLOAD_SET_MATTER';
export const UPLOAD_SET_CUSTODIAN = 'UPLOAD_SET_CUSTODIAN';
export const UPLOAD_SET_PREFIX = 'UPLOAD_SET_PREFIX';
export const UPLOAD_SET_DATABASE = 'UPLOAD_SET_DATABASE';

export const EXTRACT_ALL_META = 'EXTRACT_ALL_META';
export const EXTRACT_ALL_TEXT = 'EXTRACT_ALL_TEXT';
export const EXTRACT_SELECTED_META = 'EXTRACT_SELECTED_META';
export const EXTRACT_SELECTED_TEXT = 'EXTRACT_SELECTED_TEXT';

export const ANALYSIS_TOKENIZE_TEXT = 'ANALYSIS_TOKENIZE_TEXT';
export const ANALYSIS_TRANSLATE = 'ANALYSIS_TRANSLATE';
export const ANALYSIS_ALLOW_LSA ='ANALYSIS_ALLOW_LSA';
export const ANALYSIS_CREATE_CORPUS = 'ANALYSIS_CREATE_CORPUS';
export const ANALYSIS_SEMANTIC_ANALYSIS = 'ANALYSIS_SEMANTIC_ANALYSIS';

export const IMAGE_ALL_PDF = 'IMAGE_ALL_PDF';
export const IMAGE_ALL_HTML = 'IMAGE_ALL_HTML';
export const IMAGE_SELECTED_PDF = 'IMAGE_SELECTED_META';
export const IMAGE_SELECTED_HTML = 'IMAGE_SELECTED_HTML';

export const EXCEPTION_COLLECT_PASSWORD = 'EXCEPTION_COLLECT_PASSWORD';
export const EXCEPTION_DEDUPE = 'EXCEPTION_DEDUPE';
export const EXCEPTION_IMAGE_LARGE_FILE = 'EXCEPTION_IMAGE_LARGE_FILE';

export const UPLOAD_PANEL_TOGGLE = 'UPLOAD_PANEL_TOGGLE';
export const UPLOAD_PANEL_OPEN = 'UPLOAD_PANEL_OPEN';
export const UPLOAD_PANEL_CLOSE = 'UPLOAD_PANEL_CLOSE';
export const PROCESSING_FORM_PANEL_OPEN = 'PROCESSING_FORM_PANEL_OPEN';
export const PROCESSING_FORM_PANEL_TOGGLE = 'PROCESSING_FORM_PANEL_TOGGLE';
export const PROCESSING_FORM_PANEL_CLOSE = 'PROCESSING_FORM_PANEL_CLOSE';
export const EXTRACTION_PANEL_OPEN = 'EXTRACTION_PANEL_OPEN';
export const EXTRACTION_PANEL_TOGGLE = 'EXTRACTION_PANEL_TOGGLE';
export const EXTRACTION_PANEL_CLOSE = 'EXTRACTION_PANEL_CLOSE';
export const CONVERSION_PANEL_OPEN = 'CONVERSION_PANEL_OPEN';
export const CONVERSION_PANEL_TOGGLE = 'CONVERSION_PANEL_TOGGLE';
export const CONVERSION_PANEL_CLOSE = 'CONVERSION_PANEL_CLOSE';
export const ANALYSIS_PANEL_OPEN = 'ANALYSIS_PANEL_OPEN';
export const ANALYSIS_PANEL_TOGGLE = 'ANALYSIS_PANEL_TOGGLE';
export const ANALYSIS_PANEL_CLOSE = 'ANALYSIS_PANEL_CLOSE';
export const EXCEPTION_PANEL_OPEN = 'EXCEPTION_PANEL_OPEN';
export const EXCEPTION_PANEL_TOGGLE = 'EXCEPTION_PANEL_TOGGLE';
export const EXCEPTION_PANEL_CLOSE = 'EXCEPTION_PANEL_CLOSE';