export const SET_FB_LEFT_CONTENT = 'SET_FB_LEFT_CONTENT';
export const SET_FB_RIGHT_CONTENT = 'SET_FB_RIGHT_CONTENT';
export const SET_FB_MAIN_CONTENT = 'SET_FB_MAIN_CONTENT';

export const EDIT_FB_SECTION_LABEL = 'EDIT_FB_SECTION_LABEL';
export const SET_FB_SECTION_LABEL = 'SET_FB_SECTION_LABEL';
export const EDIT_FB_SECTION_FIELD = 'EDIT_SECTION_FIELD';
export const SET_FB_SECTION_FIELD_LABEL = 'SET_SECTION_FIELD_LABEL';
export const EDIT_FB_SECTION_FIELD_OPTIONS = 'EDIT_SECTION_FIELD_OPTIONS';
export const ADD_FB_SECTION_FIELD_OPTION = 'ADD_SECTION_FIELD_OPTION';