export const UPLOAD_QUEUE_ADD_FILE = 'UPLOAD_QUEUE_ADD_FILE';
export const UPLOAD_QUEUE_ADD_MULTIPLE = 'UPLOAD_QUEUE_ADD_MULTIPLE';
export const UPLOAD_QUEUE_REMOVE_FILE = 'UPLOAD_QUEUE_REMOVE_FILE';

export const UPLOAD_QUEUE_SELECT = 'UPLOAD_QUEUE_SELECT';

export const UPLOAD_QUEUE_REMOVE_SELECTED = 'UPLOAD_QUEUE_REMOVE_SELECTED';
export const UPLOAD_QUEUE_START_SELECTED = 'UPLOAD_QUEUE_START_SELECTED';
export const UPLOAD_QUEUE_CANCEL_SELECTED = 'UPLOAD_QUEUE_CANCEL_SELECTED';
export const UPLOAD_QUEUE_RESUME_SELECTED = 'UPLOAD_QUEUE_RESUME_SELECTED';
export const UPLOAD_QUEUE_PAUSE_SELECTED = 'UPLOAD_QUEUE_PAUSE_SELECTED';

export const UPLOAD_QUEUE_REMOVE_ALL = 'UPLOAD_QUEUE_REMOVE_ALL';
export const UPLOAD_QUEUE_START_ALL = 'UPLOAD_QUEUE_START_ALL';
export const UPLOAD_QUEUE_PAUSE_ALL = 'UPLOAD_QUEUE_PAUSE_ALL';
export const UPLOAD_QUEUE_RESUME_ALL = 'UPLOAD_QUEUE_RESUME_ALL';
export const UPLOAD_QUEUE_CANCEL_ALL = 'UPLOAD_QUEUE_CANCEL_ALL';

export const UPLOAD_FILE_START = 'UPLOAD_FILE_START';
export const UPLOAD_FILE_PAUSE = 'UPLOAD_FILE_PAUSE';
export const UPLOAD_FILE_CANCEL = 'UPLOAD_FILE_CANCEL';
export const UPLOAD_FILE_RESUME = 'UPLOAD_FILE_RESUME';

export const UPLOAD_DIALOG_OPEN = 'UPLOAD_DIALOG_OPEN';