
// MAIN CONTENT LAYOUT
export const LAYOUT_MAIN_SCROLLING = 'LAYOUT_MAIN_SCROLLING';

// SIDE CONTENT LAYOUT
export const LAYOUT_CLOSE_LEFT_ONLY = 'LAYOUT_CLOSE_LEFT_ONLY';
export const LAYOUT_CLOSE_RIGHT_ONLY = 'LAYOUT_CLOSE_RIGHT_ONLY';
export const LAYOUT_CLOSE_SIDE_CONTENT = 'LAYOUT_CLOSE_SIDE_CONTENT';
export const LAYOUT_OPEN_LEFT_ONLY = 'LAYOUT_OPEN_LEFT_ONLY';
export const LAYOUT_OPEN_RIGHT_ONLY = 'LAYOUT_OPEN_RIGHT_ONLY';
export const LAYOUT_OPEN_SIDE_CONTENT = 'LAYOUT_OPEN_SIDE_CONTENT';

// UTILITY LAYOUT
export const LAYOUT_OPEN_UTILITY = 'LAYOUT_OPEN_UTILITY';
export const LAYOUT_CLOSE_UTILITY = 'LAYOUT_CLOSE_UTILITY';

// CHAT LAYOUT
export const LAYOUT_OPEN_CHAT_BOX = 'LAYOUT_OPEN_CHAT_BOX';
export const LAYOUT_CLOSE_CHAT_BOX = 'LAYOUT_CLOSE_CHAT_BOX';
export const LAYOUT_MINIMIZE_CHAT_BOX = 'LAYOUT_MINIMIZE_CHAT_BOX';

// MEETING LAYOUT
export const LAYOUT_OPEN_MEETING_ONE_VIDEO = 'LAYOUT_OPEN_MEETING_ONE_VIDEO';
export const LAYOUT_OPEN_MEETING_TWO_VIDEOS = 'LAYOUT_OPEN_MEETING_TWO_VIDEOS';
export const LAYOUT_OPEN_MEETING_THREE_VIDEOS = 'LAYOUT_OPEN_MEETING_THREE_VIDEOS';
export const LAYOUT_OPEN_MEETING_FOUR_VIDEOS = 'LAYOUT_OPEN_MEETING_FOUR_VIDEOS';
export const LAYOUT_OPEN_MEETING_FIVE_VIDEOS = 'LAYOUT_OPEN_MEETING_FIVE_VIDEOS';
export const LAYOUT_OPEN_MEETING_SIX_VIDEOS = 'LAYOUT_OPEN_MEETING_SIX_VIDEOS';
export const LAYOUT_OPEN_MEETING_SEVEN_VIDEOS = 'LAYOUT_OPEN_MEETING_SEVEN_VIDEOS';
export const LAYOUT_OPEN_MEETING_EIGHT_VIDEOS = 'LAYOUT_OPEN_MEETING_EIGHT_VIDEOS';
export const LAYOUT_OPEN_MEETING_NINE_VIDEOS = 'LAYOUT_OPEN_MEETING_NINE_VIDEOS';
export const LAYOUT_OPEN_MEETING_TEN_VIDEOS = 'LAYOUT_OPEN_MEETING_TEN_VIDEOS';