//	Layout
export const THEME 											= 'THEME';
export const SET_VIEW										= 'SET_VIEW';
export const SET_TITLE										= 'SET_TITLE';
export const RESIZE											= 'RESIZE';
export const SET_PAGE										= 'SET_PAGE';
export const LEFT_SIDEBAR_TOGGLE 							= 'LEFT_SIDEBAR_TOGGLE';
export const LEFT_SIDEBAR_SET_WIDTH 						= 'LEFT_SIDEBAR_SET_WIDTH';
export const LEFT_SIDEBAR_CLOSE								= 'LEFT_SIDEBAR_CLOSE';
export const LEFT_SIDEBAR_OPEN								= 'LEFT_SIDEBAR_OPEN';
export const LEFT_SIDEBAR_DOCK								= 'LEFT_SIDEBAR_DOCK';
export const LEFT_SIDEBAR_UNDOCK							= 'LEFT_SIDEBAR_UNDOCK';
export const LEFT_SIDEBAR_MINIMIZE							= 'LEFT_SIDEBAR_MINIMIZE';
export const LEFT_SIDEBAR_MAXIMIZE							= 'LEFT_SIDEBAR_MAXIMIZE';
export const LEFT_SIDEBAR_SET_DESKTOP						= 'LEFT_SIDEBAR_SET_DESKTOP';
export const LEFT_SIDEBAR_SET_TABLET						= 'LEFT_SIDEBAR_SET_TABLET';
export const LEFT_SIDEBAR_SET_MOBILE						= 'LEFT_SIDEBAR_SET_MOBILE';
export const LEFT_TROUGH_TOGGLE 							= 'LEFT_TROUGH_TOGGLE';
export const LEFT_TROUGH_OPEN								= 'LEFT_TROUGH_OPEN';
export const LEFT_TROUGH_CLOSE								= 'LEFT_TROUGH_CLOSE';
export const LEFT_TROUGH_SET_WIDTH 							= 'LEFT_TROUGH_SET_WIDTH';
export const LEFT_TROUGH_SET_TYPE							= 'LEFT_TROUGH_SET_TYPE';
export const RIGHT_SIDEBAR_TOGGLE 							= 'RIGHT_SIDEBAR_TOGGLE';
export const RIGHT_SIDEBAR_SET_WIDTH 						= 'RIGHT_SIDEBAR_SET_WIDTH';
export const RIGHT_TROUGH_OPEN								= 'RIGHT_TROUGH_OPEN';
export const RIGHT_TROUGH_CLOSE								= 'RIGHT_TROUGH_CLOSE';
export const RIGHT_TROUGH_TOGGLE 							= 'RIGHT_TROUGH_TOGGLE';
export const RIGHT_TROUGH_SET_TYPE							= 'RIGHT_TROUGH_SET_TYPE';
export const RIGHT_TROUGH_SET_WIDTH 						= 'RIGHT_TROUGH_SET_WIDTH';
export const RIGHT_TROUGH_SET_LOCATION						= 'RIGHT_TROUGH_SET_LOCATION';
export const RIGHT_TROUGH_SET_VISIBILITY					= 'RIGHT_TROUGH_SET_VISIBILITY';

export const TROUGHS_OPEN									= 'TROUGHS_OPEN';

export const PAGE_SET_DESKTOP								= 'PAGE_SET_DESKTOP';
export const PAGE_SET_TABLET								= 'PAGE_SET_TABLET';
export const PAGE_SET_MOBILE								= 'PAGE_SET_MOBILE';

export const PRIMARY_SET_WIDTH 								= 'PRIMARY_SET_WIDTH';
export const PRIMARY_SET_LOCATION							= 'PRIMARY_SET_LOCATION';

//	User
export const SET_USER 										= 'SET_USER';
export const SET_USER_LINKS									= 'SET_USER_LINKS';
export const SET_LOGIN_EMAIL								= 'SET_LOGIN_EMAIL';
export const SET_LOGIN_PASSWORD								= 'SET_LOGIN_PASSWORD';
export const LOGIN 											= 'LOGIN';
export const REMOVE_USER									= 'REMOVE_USER';
export const SET_LOGIN_ERROR								= 'SET_LOGIN_ERROR';
export const SET_LOGIN_ERROR_CLOSE							= 'SET_LOGIN_ERROR_CLOSE';
export const CLEAR_LOGIN_ERROR								= 'CLEAR_LOGIN_ERROR';

//	Client General
export const SET_CLIENT_TYPE 								= 'SET_CLIENT_TYPE';
export const SET_CLIENT_SAVING_ERROR 						= 'SET_CLIENT_SAVING_ERROR';

//	Client Individual
export const SET_CLIENT_INDIVIDUAL_FIRST_NAME 				= 'SET_CLIENT_INDIVIDUAL_FIRST_NAME';
export const SET_CLIENT_INDIVIDUAL_MIDDLE_NAME 				= 'SET_CLIENT_INDIVIDUAL_MIDDLE_NAME';
export const SET_CLIENT_INDIVIDUAL_LAST_NAME 				= 'SET_CLIENT_INDIVIDUAL_LAST_NAME';
export const SET_CLIENT_INDIVIDUAL_ADDRESS 					= 'SET_CLIENT_INDIVIDUAL_ADDRESS';
export const SET_CLIENT_INDIVIDUAL_CITY 					= 'SET_CLIENT_INDIVIDUAL_CITY';
export const SET_CLIENT_INDIVIDUAL_STATE 					= 'SET_CLIENT_INDIVIDUAL_STATE';
export const SET_CLIENT_INDIVIDUAL_ZIP 						= 'SET_CLIENT_INDIVIDUAL_ZIP';
export const SET_CLIENT_INDIVIDUAL_PHONE 					= 'SET_CLIENT_INDIVIDUAL_PHONE';
export const SET_CLIENT_INDIVIDUAL_EMAIL 					= 'SET_CLIENT_INDIVIDUAL_EMAIL';
export const SET_CLIENT_INDIVIDUAL_AVATAR 					= 'SET_CLIENT_INDIVIDUAL_AVATAR';

//	Client Business
export const SET_CLIENT_BUSINESS_NAME 						= 'SET_CLIENT_BUSINESS_NAME';
export const SET_CLIENT_BUSINESS_ADDRESS 					= 'SET_CLIENT_BUSINESS_ADDRESS';
export const SET_CLIENT_BUSINESS_STATE						= 'SET_CLIENT_BUSINESS_STATE';
export const SET_CLIENT_BUSINESS_ZIP						= 'SET_CLIENT_BUSINESS_ZIP';
export const SET_CLIENT_BUSINESS_PHONE 						= 'SET_CLIENT_BUSINESS_PHONE';
export const SET_CLIENT_BUSINESS_LOGO 						= 'SET_CLIENT_BUSINESS_LOGO';
export const SET_CLIENT_BUSINESS_PRINCIPLE_FIRST_NAME 		= 'SET_CLIENT_BUSINESS_PRINCIPLE_FIRST_NAME';
export const SET_CLIENT_BUSINESS_PRINCIPLE_MIDDLE_NAME 		= 'SET_CLIENT_BUSINESS_PRINCIPLE_MIDDLE_NAME';
export const SET_CLIENT_BUSINESS_PRINCIPLE_LAST_NAME 		= 'SET_CLIENT_BUSINESS_PRINCIPLE_LAST_NAME';
export const SET_CLIENT_BUSINESS_PRINCIPLE_TITLE 			= 'SET_CLIENT_BUSINESS_PRINCIPLE_TITLE';
export const SET_CLIENT_BUSINESS_INDUSTRY 					= 'SET_CLIENT_BUSINESS_INDUSTRY';

//	Floating Action Button
export const FAB_TOGGLE										= 	'FAB_TOGGLE';
export const FAB_START_TRANSITION							=	'FAB_START_TRANSITION';
export const FAB_STOP_TRANSITION							= 	'FAB_STOP_TRANSITION';
export const FAB_OPEN										=	'FAB_OPEN';
export const FAB_CLOSE										=	'FAB_CLOSE';
export const FAB_SET_ICON									=	'FAB_SET_ICON';
export const FAB_SET_ITEMS									=	'FAB_SET_ITEMS';

//	Discovery Page
export const DISCOVERY_SET_ACTIVE_PANEL 					= 'DISCOVERY_SET_ACTIVE_PANEL';
export const DISCOVERY_SET_DOCUMENT_LIST 					= 'DISCOVERY_SET_DOCUMENT_LIST';
export const DISCOVERY_SET_NUMBER_OF_DOCUMENTS 				= 'DISCOVERY_SET_NUMBER_OF_DOCUMENTS';
export const DISCOVERY_SET_CURRENT_DOCUMENT 				= 'DISCOVERY_SET_CURRENT_DOCUMENT';
export const DISCOVERY_SET_SELECTED_DOCUMENTS 				= 'DISCOVERY_SET_SELECTED_DOCUMENTS';
export const DISCOVERY_SET_CURRENT_DOCUMENT_NUMBER 			= 'DISCOVERY_SET_CURRENT_DOCUMENT_NUMBER';
export const DISCOVERY_NEXT_DOCUMENT 						= 'DISCOVERY_NEXT_DOCUMENT';
export const DISCOVERY_PREVIOUS_DOCUMENT 					= 'DISCOVERY_PREVIOUS_DOCUMENT';
export const DISCOVERY_FIRST_DOCUMENT 						= 'DISCOVERY_FIRST_DOCUMENT';
export const DISCOVERY_LAST_DOCUMENT 						= 'DISCOVERY_LAST_DOCUMENT';
export const DISCOVERY_SET_BATCH_LIST 						= 'DISCOVERY_SET_BATCH_LIST';
export const DISCOVERY_SET_FORM_LIST 						= 'DISCOVERY_SET_FORM_LIST';

//	File Tree
export const SET_ACTIVE_TREE_ITEM							= 'SET_ACTIVE_TREE_ITEM';
export const ADD_EXPANDED_TREE_ITEM 						= 'ADD_EXPANDED_TREE_ITEM';
export const REMOVE_EXPANDED_TREE_ITEM						= 'REMOVE_EXPANDED_TREE_ITEM';
export const SET_ACTIVE_SEARCH 								= 'SET_ACTIVE_SEARCH';
export const FILE_TREE_COLLAPSE 							= 'FILE_TREE_COLLAPSE';
export const SET_TREE 										= 'SET_TREE';
export const OPEN_FILE_TREE_CONTEXT							= 'OPEN_FILE_TREE_CONTEXT';
export const CLOSE_FILE_TREE_CONTEXT						= 'CLOSE_FILE_TREE_CONTEXT';

//	Matter
export const SET_MATTER_NAME 								= 'SET_MATTER_NAME';
export const SET_MATTER_TYPE 								= 'SET_MATTER_TYPE';
export const SET_MATTER_DESCRIPTION 						= 'SET_MATTER_DESCRIPTION';
export const ADD_MATTER_KEYWORD 							= 'ADD_MATTER_KEYWORD';
export const REMOVE_MATTER_KEYWORD 							= 'REMOVE_MATTER_KEYWORD';
export const SET_MATTER_STAGE 								= 'SET_MATTER_STAGE';
export const SET_MATTER_CLIENT 								= 'SET_MATTER_CLIENT';
export const SET_MATTER_EXISTING_CLIENT 					= 'SET_MATTER_EXISTING_CLIENT';
export const SET_MATTER_CASE 								= 'SET_MATTER_CASE';
export const SET_MATTER_USE_VENDORS 						= 'SET_MATTER_USE_VENDORS';
export const SET_MATTER_EXISTING_CASE 						= 'SET_MATTER_EXISTING_CASE';
export const SET_MATTER_EXISTING_VENDOR 					= 'SET_MATTER_EXISTING_VENDOR';
export const SET_MATTER_FORM_STEP_INDEX 					= 'SET_MATTER_FORM_STEP_INDEX';
export const MATTER_FORM_NEXT_STEP 							= 'MATTER_FORM_NEXT_STEP';
export const MATTER_FORM_PREVIOUS_STEP 						= 'MATTER_FORM_PREVIOUS_STEP';
export const SET_MATTER_FORM_LOADING 						= 'SET_MATTER_FORM_LOADING';
export const SET_MATTER_FORM_FINISHED 						= 'SET_MATTER_FORM_FINISHED';
export const SET_MATTER_GENERAL_SAVING_ERROR 				= 'SET_MATTER_GENERAL_SAVING_ERROR';
export const SET_MATTER_DETAILS_SAVING_ERROR 				= 'SET_MATTER_DETAILS_SAVING_ERROR';
export const SET_MATTER_CASE_SAVING_ERROR 					= 'SET_MATTER_CASE_SAVING_ERROR';
export const SET_MATTER_VENDORS_SAVING_ERROR 				= 'SET_MATTER_VENDORS_SAVING_ERROR';
export const SET_MATTER_DISCOVERY_SAVING_ERROR 				= 'SET_MATTER_DISCOVERY_SAVING_ERROR';
export const SET_MATTER_CLIENT_SAVING_ERROR 				= 'SET_MATTER_CLIENT_SAVING_ERROR';
export const MATTER_GENERAL_SAVED 							= 'MATTER_GENERAL_SAVED';
export const MATTER_DETAILS_SAVED 							= 'MATTER_DETAILS_SAVED';
export const MATTER_CLIENT_SAVED 							= 'MATTER_CLIENT_SAVED';
export const MATTER_CASE_SAVED 								= 'MATTER_CASE_SAVED';
export const MATTER_DISCOVERY_SAVED 						= 'MATTER_DISCOVERY_SAVED';

//	Matter Form
export const SET_MATTER_FORM_STEP 							= 'SET_MATTER_FORM_STEP';
export const NEXT_MATTER_FORM_STEP 							= 'NEXT_MATTER_FORM_STEP';
export const PREVIOUS_MATTER_FORM_STEP 						= 'PREVIOUS_MATTER_FORM_STEP';
export const SET_MATTER_KEYWORDS 							= 'SET_MATTER_KEYWORDS';
export const SET_MATTER_CLIENT_EXISTING 					= 'SET_MATTER_CLIENT_EXISTING';
export const SET_MATTER_CASE_EXISTING 						= 'SET_MATTER_CASE_EXISTING';
export const SET_MATTER_SELECTED 							= 'SET_MATTER_SELECTED';
export const SET_MATTER_LIST 								= 'SET_MATTER_LIST';
export const CLEAR_SELECTED_MATTER 							= 'CLEAR_SELECTED_MATTER';
export const SET_MATTER_SEARCHES 							= 'SET_MATTER_SEARCHES';
export const SET_MATTER_SEARCHES_ERROR 						= 'SET_MATTER_SEARCHES_ERROR';

//	Processing
export const UPLOAD_QUEUE_ADD_FILE 							= 'UPLOAD_QUEUE_ADD_FILE';
export const UPLOAD_QUEUE_ADD_MULTIPLE 						= 'UPLOAD_QUEUE_ADD_MULTIPLE';
export const UPLOAD_QUEUE_REMOVE_FILE 						= 'UPLOAD_QUEUE_REMOVE_FILE';
export const UPLOAD_QUEUE_SELECT 							= 'UPLOAD_QUEUE_SELECT';
export const UPLOAD_QUEUE_FILE_INFO 						= 'UPLOAD_QUEUE_FILE_INFO';
export const UPLOAD_QUEUE_FILE_INFO_REMOVE 					= 'UPLOAD_QUEUE_FILE_INFO_REMOVE';
export const UPLOAD_QUEUE_MOVE_WAIT_TO_INPROGRESS 			= 'UPLOAD_QUEUE_MOVE_WAIT_TO_INPROGRESS';
export const UPLOAD_QUEUE_UPDATE_FILE_STATUS_COMPLETE 		= 'UPLOAD_QUEUE_UPDATE_FILE_STATUS_COMPLETE';
export const UPLOAD_QUEUE_REMOVE_SELECTED 					= 'UPLOAD_QUEUE_REMOVE_SELECTED';
export const UPLOAD_QUEUE_START_SELECTED 					= 'UPLOAD_QUEUE_START_SELECTED';
export const UPLOAD_QUEUE_CANCEL_SELECTED 					= 'UPLOAD_QUEUE_CANCEL_SELECTED';
export const UPLOAD_QUEUE_RESUME_SELECTED	 				= 'UPLOAD_QUEUE_RESUME_SELECTED';
export const UPLOAD_QUEUE_PAUSE_SELECTED 					= 'UPLOAD_QUEUE_PAUSE_SELECTED';
export const UPLOAD_QUEUE_REMOVE_ALL 						= 'UPLOAD_QUEUE_REMOVE_ALL';
export const UPLOAD_QUEUE_START_ALL 						= 'UPLOAD_QUEUE_START_ALL';
export const UPLOAD_QUEUE_START_ALL_W_WAIT 					= 'UPLOAD_QUEUE_START_ALL_W_WAIT';
export const UPLOAD_QUEUE_START_ALL_W_OUT_WAIT 				= 'UPLOAD_QUEUE_START_ALL_W_OUT_WAIT';
export const UPLOAD_QUEUE_PAUSE_ALL 						= 'UPLOAD_QUEUE_PAUSE_ALL';
export const UPLOAD_QUEUE_RESUME_ALL 						= 'UPLOAD_QUEUE_RESUME_ALL';
export const UPLOAD_QUEUE_CANCEL_ALL 						= 'UPLOAD_QUEUE_CANCEL_ALL';
export const UPLOAD_FILE_START 								= 'UPLOAD_FILE_START';
export const UPLOAD_FILE_PAUSE 								= 'UPLOAD_FILE_PAUSE';
export const UPLOAD_FILE_CANCEL 							= 'UPLOAD_FILE_CANCEL';
export const UPLOAD_FILE_RESUME 							= 'UPLOAD_FILE_RESUME';
export const UPLOAD_DIALOG_OPEN 							= 'UPLOAD_DIALOG_OPEN';
export const UPLOAD_SET_MATTER 								= 'UPLOAD_SET_MATTER';
export const UPLOAD_SET_CUSTODIAN 							= 'UPLOAD_SET_CUSTODIAN';
export const UPLOAD_SET_PREFIX 								= 'UPLOAD_SET_PREFIX';
export const UPLOAD_SET_DATABASE 							= 'UPLOAD_SET_DATABASE';
export const EXTRACT_ALL_META 								= 'EXTRACT_ALL_META';
export const EXTRACT_ALL_TEXT 								= 'EXTRACT_ALL_TEXT';
export const EXTRACT_SELECTED_META 							= 'EXTRACT_SELECTED_META';
export const EXTRACT_SELECTED_TEXT 							= 'EXTRACT_SELECTED_TEXT';
export const ANALYSIS_TOKENIZE_TEXT 						= 'ANALYSIS_TOKENIZE_TEXT';
export const ANALYSIS_TRANSLATE 							= 'ANALYSIS_TRANSLATE';
export const ANALYSIS_ALLOW_LSA	 							= 'ANALYSIS_ALLOW_LSA';
export const ANALYSIS_CREATE_CORPUS 						= 'ANALYSIS_CREATE_CORPUS';
export const ANALYSIS_SEMANTIC_ANALYSIS 					= 'ANALYSIS_SEMANTIC_ANALYSIS';
export const IMAGE_ALL_PDF 									= 'IMAGE_ALL_PDF';
export const IMAGE_ALL_HTML 								= 'IMAGE_ALL_HTML';
export const IMAGE_SELECTED_PDF 							= 'IMAGE_SELECTED_META';
export const IMAGE_SELECTED_HTML 							= 'IMAGE_SELECTED_HTML';
export const EXCEPTION_COLLECT_PASSWORD 					= 'EXCEPTION_COLLECT_PASSWORD';
export const EXCEPTION_DEDUPE 								= 'EXCEPTION_DEDUPE';
export const EXCEPTION_IMAGE_LARGE_FILE 					= 'EXCEPTION_IMAGE_LARGE_FILE';
export const UPLOAD_PANEL_TOGGLE 							= 'UPLOAD_PANEL_TOGGLE';
export const UPLOAD_PANEL_OPEN 								= 'UPLOAD_PANEL_OPEN';
export const UPLOAD_PANEL_CLOSE 							= 'UPLOAD_PANEL_CLOSE';
export const PROCESSING_FORM_PANEL_OPEN 					= 'PROCESSING_FORM_PANEL_OPEN';
export const PROCESSING_FORM_PANEL_TOGGLE 					= 'PROCESSING_FORM_PANEL_TOGGLE';
export const PROCESSING_FORM_PANEL_CLOSE 					= 'PROCESSING_FORM_PANEL_CLOSE';
export const EXTRACTION_PANEL_OPEN 							= 'EXTRACTION_PANEL_OPEN';
export const EXTRACTION_PANEL_TOGGLE 						= 'EXTRACTION_PANEL_TOGGLE';
export const EXTRACTION_PANEL_CLOSE 						= 'EXTRACTION_PANEL_CLOSE';
export const CONVERSION_PANEL_OPEN 							= 'CONVERSION_PANEL_OPEN';
export const CONVERSION_PANEL_TOGGLE 						= 'CONVERSION_PANEL_TOGGLE';
export const CONVERSION_PANEL_CLOSE 						= 'CONVERSION_PANEL_CLOSE';
export const ANALYSIS_PANEL_OPEN 							= 'ANALYSIS_PANEL_OPEN';
export const ANALYSIS_PANEL_TOGGLE 							= 'ANALYSIS_PANEL_TOGGLE';
export const ANALYSIS_PANEL_CLOSE 							= 'ANALYSIS_PANEL_CLOSE';
export const EXCEPTION_PANEL_OPEN 							= 'EXCEPTION_PANEL_OPEN';
export const EXCEPTION_PANEL_TOGGLE 						= 'EXCEPTION_PANEL_TOGGLE';
export const EXCEPTION_PANEL_CLOSE 							= 'EXCEPTION_PANEL_CLOSE';

//	Search
export const SEARCH_SET 									= 'SEARCH_SET';
export const SEARCH_REMOVE 									= 'SEARCH_REMOVE';
export const SEARCH_SET_NAME 								= 'SEARCH_SET_NAME';
export const SEARCH_SET_TEXT 								= 'SEARCH_SET_TEXT';
export const SEARCH_SET_IS_CACHED 							= 'SEARCH_SET_IS_CACHED';
export const SEARCH_SET_CACHE 								= 'SEARCH_SET_CACHE';
export const SEARCH_SET_INCLUDED 							= 'SEARCH_SET_INCLUDED';
export const SEARCH_SET_SCOPE 								= 'SEARCH_SET_SCOPE';
export const SEARCH_SET_PRIVATE 							= 'SEARCH_SET_PRIVATE';
export const SEARCH_SET_PUBLIC 								= 'SEARCH_SET_PUBLIC';
export const SEARCH_SET_FILTER_RULES 						= 'SEARCH_SET_FILTER_RULES';
export const SEARCH_SET_FILTERS 							= 'SEARCH_SET_FILTERS';
export const SEARCH_ADD_FILTER_GROUP 						= 'SEARCH_ADD_FILTER_GROUP';
export const SEARCH_ADD_FILTER_RULE 						= 'SEARCH_ADD_FILTER_RULE';
export const SEARCH_REMOVE_FILTER_GROUP 					= 'SEARCH_ADD_FILTER_GROUP';
export const SEARCH_REMOVE_FILTER_RULE 						= 'SEARCH_REMOVE_FILTER_RULE';
export const SEARCH_SET_COLUMNS 							= 'SEARCH_SET_COLUMNS';
export const SEARCH_SET_COLUMN_ORDER 						= 'SEARCH_SET_COLUMN_ORDER';
export const SEARCH_IS_RERUN_REQUIRED 						= 'SEARCH_IS_RERUN_REQUIRED';
export const SEARCH_IS_CACHED 								= 'SEARCH_IS_CACHED';
export const SEARCH_IS_AUTO_UPDATE 							= 'SEARCH_IS_AUTO_UPDATE';
export const SEARCH_SET_SORT 								= 'SEARCH_SET_SORT';

//	Video Chat
export const SET_REMOTE_VIDEO 								= 'SET_REMOTE_VIDEO';
export const ADD_REMOTE_STREAM 								= 'ADD_REMOTE_STREAM';
export const UPDATE_REMOTE_STREAM 							= 'UPDATE_REMOTE_STREAM';
export const REMOVE_REMOTE_STREAM 							= 'REMOVE_REMOTE_STREAM';
export const GET_LOCAL_STREAM 								= 'GET_LOCAL_STREAM';
export const SET_LOCAL_STREAM 								= 'SET_LOCAL_STREAM';
export const STOP_LOCAL_STREAM 								= 'STOP_LOCAL_STREAM';
export const LOCAL_STREAM_ERROR 							= 'LOCAL_STREAM_ERROR';
export const LEAVE_MEETING_STREAM 							= 'LEAVE_MEETING_STREAM';
export const TOGGLE_LOCAL_AUDIO 							= 'TOGGLE_LOCAL_AUDIO';
export const TOGGLE_REMOTE_AUDIO 							= 'TOGGLE_REMOTE_AUDIO';
export const TOGGLE_LOCAL_VIDEO 							= 'TOGGLE_LOCAL_VIDEO';
export const JOIN_MEETING_STREAM 							= 'JOIN_MEETING_STREAM';

//	Document Viewer
export const VIEWER_OPEN 									= 'VIEWER_OPEN';
export const VIEWER_CLOSE 									= 'VIEWER_CLOSE';
export const VIEWER_SET_TYPE 								= 'VIEWER_SET_TYPE';
export const VIEWER_SET_DOCUMENT 							= 'VIEWER_SET_DOCUMENT';
export const VIEWER_SET_PAGES 								= 'VIEWER_SET_PAGES';
export const VIEWER_SET_ACTIVE_PAGE 						= 'VIEWER_SET_ACTIVE_PAGE';
export const VIEWER_ROTATE_CLOCKWISE 						= 'VIEWER_ROTATE_CLOCKWISE';
export const VIEWER_ROTATE_COUNTER_CLOCKWISE 				= 'VIEWER_ROTATE_COUNTER_CLOCKWISE';
export const VIEWER_ZOOM_IN 								= 'VIEWER_ZOOM_IN';
export const VIEWER_ZOOM_OUT 								= 'VIEWER_ZOOM_OUT';
export const VIEWER_SET_ZOOM 								= 'VIEWER_SET_ZOOM';
export const VIEWER_NEXT_PAGE 								= 'VIEWER_NEXT_PAGE';
export const VIEWER_PREVIOUS_PAGE 							= 'VIEWER_PREVIOUS_PAGE';
export const VIEWER_HIGHLIGHT_SET_DISPLAY 					= 'VIEWER_HIGHLIGHT_SET_DISPLAY';
export const VIEWER_HIGHLIGHT_SET_HIDE 						= 'VIEWER_HIGHLIGHT_SET_HIDE';
export const VIEWER_USER_HIGHLIGHT_CREATE 					= 'VIEWER_USER_HIGHLIGHT_CREATE';
export const VIEWER_USER_HIGHLIGHT_REMOVE 					= 'VIEWER_USER_HIGHLIGHT_REMOVE';
export const VIEWER_REDACTION_CREATE 						= 'VIEWER_REDACTION_CREATE';
export const VIEWER_REDACTION_REMOVE 						= 'VIEWER_REDACTION_REMOVE';
export const VIEWER_REDACTION_SET_LABEL 					= 'VIEWER_REDACTION_SET_LABEL';

//	Form Builder
export const SET_DRAG_STATUS 								= "SET_DRAG_STATUS";
export const FIELD_ADD 										= "FIELD_ADD";
export const FIELD_REMOVE 									= "FIELD_REMOVE";
export const FIELD_UPDATE 									= "FIELD_UPDATE";
export const FIELD_INSERT 									= "FIELD_INSERT";
export const FIELD_SWAP 									= "FIELD_SWAP";
export const FORM_RESET 									= "FORM_RESET";
export const FORM_UPDATE_TITLE 								= "FORM_UPDATE_TITLE";
export const FORM_UPDATE_DESCRIPTION 						= "FORM_UPDATE_DESCRIPTION";
export const NOTIFICATION_ADD 								= "NOTIFICATION_ADD";
export const NOTIFICATION_REMOVE 							= "NOTIFICATION_REMOVE";
export const FORM_PUBLISH 									= "FORM_PUBLISH";

export const FORM_PUBLICATION_PENDING 						= "FORM_PUBLICATION_PENDING";
export const FORM_PUBLICATION_DONE 							= "FORM_PUBLICATION_DONE";
export const FORM_PUBLICATION_FAILED 						= "FORM_PUBLICATION_FAILED";

export const FORM_RECORD_CREATION_PENDING 					= "FORM_RECORD_CREATION_PENDING";
export const FORM_RECORD_CREATION_DONE 						= "FORM_RECORD_CREATION_DONE";

export const SCHEMA_RETRIEVAL_PENDING 						= "SCHEMA_RETRIEVAL_PENDING";
export const SCHEMA_RETRIEVAL_DONE 							= "SCHEMA_RETRIEVAL_DONE";

export const RECORDS_RETRIEVAL_PENDING 						= "RECORDS_RETRIEVAL_PENDING";
export const RECORDS_RETRIEVAL_DONE 						= "RECORDS_RETRIEVAL_DONE";