export const THEME 						= 	'THEME';
export const SET_VIEW					=	'SET_VIEW';
export const SET_TITLE					=	'SET_TITLE';
export const RESIZE						= 	'RESIZE';
export const SET_USER 					= 	'SET_USER';
export const SET_PAGE					=	'SET_PAGE';

export const LEFT_SIDEBAR_TOGGLE 		= 	'LEFT_SIDEBAR_TOGGLE';
export const LEFT_SIDEBAR_SET_WIDTH 	= 	'LEFT_SIDEBAR_SET_WIDTH';
export const LEFT_SIDEBAR_CLOSE			= 	'LEFT_SIDEBAR_CLOSE';
export const LEFT_SIDEBAR_OPEN			=	'LEFT_SIDEBAR_OPEN';
export const LEFT_SIDEBAR_DOCK			=	'LEFT_SIDEBAR_DOCK';
export const LEFT_SIDEBAR_UNDOCK		=	'LEFT_SIDEBAR_UNDOCK';
export const LEFT_SIDEBAR_MINIMIZE		=	'LEFT_SIDEBAR_MINIMIZE';
export const LEFT_SIDEBAR_MAXIMIZE		=	'LEFT_SIDEBAR_MAXIMIZE';
export const LEFT_SIDEBAR_SET_DESKTOP	=	'LEFT_SIDEBAR_SET_DESKTOP';
export const LEFT_SIDEBAR_SET_TABLET	=	'LEFT_SIDEBAR_SET_TABLET';
export const LEFT_SIDEBAR_SET_MOBILE	= 	'LEFT_SIDEBAR_SET_MOBILE';

export const LEFT_TROUGH_TOGGLE 		= 	'LEFT_TROUGH_TOGGLE';
export const LEFT_TROUGH_OPEN			=	'LEFT_TROUGH_OPEN';
export const LEFT_TROUGH_CLOSE			=	'LEFT_TROUGH_CLOSE';
export const LEFT_TROUGH_SET_WIDTH 		= 	'LEFT_TROUGH_SET_WIDTH';
export const LEFT_TROUGH_SET_TYPE		=	'LEFT_TROUGH_SET_TYPE';

export const RIGHT_SIDEBAR_TOGGLE 		= 	'RIGHT_SIDEBAR_TOGGLE';
export const RIGHT_SIDEBAR_SET_WIDTH 	= 	'RIGHT_SIDEBAR_SET_WIDTH';

export const RIGHT_TROUGH_OPEN			=	'RIGHT_TROUGH_OPEN';
export const RIGHT_TROUGH_CLOSE			=	'RIGHT_TROUGH_CLOSE';
export const RIGHT_TROUGH_TOGGLE 		= 	'RIGHT_TROUGH_TOGGLE';
export const RIGHT_TROUGH_SET_TYPE		=	'RIGHT_TROUGH_SET_TYPE';
export const RIGHT_TROUGH_SET_WIDTH 	= 	'RIGHT_TROUGH_SET_WIDTH';
export const RIGHT_TROUGH_SET_LOCATION	=	'RIGHT_TROUGH_SET_LOCATION';
export const RIGHT_TROUGH_SET_VISIBILITY=	'RIGHT_TROUGH_SET_VISIBILITY';

export const TROUGHS_OPEN				=	'TROUGHS_OPEN';

export const PAGE_SET_DESKTOP			=	'PAGE_SET_DESKTOP';
export const PAGE_SET_TABLET			=	'PAGE_SET_TABLET';
export const PAGE_SET_MOBILE			=	'PAGE_SET_MOBILE';

export const PRIMARY_SET_WIDTH 			= 	'PRIMARY_SET_WIDTH';
export const PRIMARY_SET_LOCATION		= 	'PRIMARY_SET_LOCATION';

export const FAB_TOGGLE					= 	'FAB_TOGGLE';
export const FAB_START_TRANSITION		=	'FAB_START_TRANSITION';
export const FAB_STOP_TRANSITION		= 	'FAB_STOP_TRANSITION';
export const FAB_OPEN					=	'FAB_OPEN';
export const FAB_CLOSE					=	'FAB_CLOSE';
export const FAB_SET_ICON				=	'FAB_SET_ICON';
export const FAB_SET_ITEMS				=	'FAB_SET_ITEMS';